import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import './globals.css'
import classNames from 'classnames'

export const metadata: Metadata = {
  title: 'Memora',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={classNames(
          'flex items-center h-screen antialiased text-[#242424] bg-[#F6F6F6]',
          poppins.className,
        )}
      >
        {children}
      </body>
    </html>
  )
}
